#! /bin/bash

mkdir -p backbone.marionette/amd

curl https://raw.github.com/douglascrockford/JSON-js/master/json2.js > backbone.marionette/json2.js
curl http://underscorejs.org/underscore.js > backbone.marionette/underscore.js
curl http://backbonejs.org/backbone.js > backbone.marionette/backbone.js
curl http://code.jquery.com/jquery.js > backbone.marionette/jquery.js
curl https://raw.github.com/marionettejs/backbone.eventbinder/master/backbone.marionette/backbone.eventbinder.js > backbone.marionette/backbone.eventbinder.js
curl https://raw.github.com/marionettejs/backbone.wreqr/master/backbone.marionette/backbone.wreqr.js > backbone.marionette/backbone.wreqr.js
curl https://raw.github.com/marionettejs/backbone.marionette/master/backbone.marionette/backbone.marionette.js > backbone.marionette/backbone.marionette.js
curl https://raw.github.com/marionettejs/backbone.marionette/master/backbone.marionette/backbone.marionette.min.js > backbone.marionette/backbone.marionette.min.js
curl https://raw.github.com/marionettejs/backbone.marionette/master/backbone.marionette/amd/backbone.marionette.js > backbone.marionette/amd/backbone.marionette.js
curl https://raw.github.com/marionettejs/backbone.marionette/master/backbone.marionette/amd/backbone.marionette.min.js > backbone.marionette/amd/backbone.marionette.min.js

rm backbone.marionette.tar.gz
rm backbone.marionette.zip

tar -zcvf backbone.marionette.tar.gz backbone.marionette/
zip -r backbone.marionette.zip backbone.marionette/
