#! /bin/bash

if [ -z "$1" ]
  then
    echo "please specify your version. example: ./build-marionette 1.0.0-beta6"
    exit
fi

# replace version in data/global.yml
sed -E -i '' -e 's/^version: (.+)/version: '$1'/g' data/global.yml

mkdir -p backbone.marionette/core

curl https://raw.github.com/douglascrockford/JSON-js/master/json2.js > backbone.marionette/json2.js
curl http://underscorejs.org/underscore.js > backbone.marionette/underscore.js
curl http://backbonejs.org/backbone.js > backbone.marionette/backbone.js
curl http://code.jquery.com/jquery.js > backbone.marionette/jquery.js
curl https://raw.github.com/marionettejs/backbone.eventbinder/master/lib/backbone.eventbinder.js > backbone.marionette/backbone.eventbinder.js
curl https://raw.github.com/marionettejs/backbone.wreqr/master/lib/backbone.wreqr.js > backbone.marionette/backbone.wreqr.js
curl https://raw.github.com/marionettejs/backbone.babysitter/master/lib/backbone.babysitter.js > backbone.marionette/backbone.babysitter.js

curl https://raw.github.com/marionettejs/backbone.marionette/master/lib/backbone.marionette.js > backbone.marionette/backbone.marionette.js
curl https://raw.github.com/marionettejs/backbone.marionette/master/lib/backbone.marionette.min.js > backbone.marionette/backbone.marionette.min.js

curl https://raw.github.com/marionettejs/backbone.marionette/master/lib/core/backbone.marionette.js > backbone.marionette/core/backbone.marionette.js
curl https://raw.github.com/marionettejs/backbone.marionette/master/lib/core/backbone.marionette.min.js > backbone.marionette/core/backbone.marionette.min.js

rm backbone.marionette.tar.gz
rm backbone.marionette.zip

tar -zcvf backbone.marionette.tar.gz backbone.marionette/
zip -r backbone.marionette.zip backbone.marionette/

rm -r source/downloads
mv backbone.marionette source/downloads
mv backbone.marionette.tar.gz source/downloads
mv backbone.marionette.zip source/downloads

rm source/downloads/backbone.js
rm source/downloads/jquery.js
rm source/downloads/json2.js
rm source/downloads/underscore.js
